In [1]:
# Customer Churn Prediction & Retension Optimisation

In [3]:
import pandas as pd
import numpy as np
df = pd.read_excel(r"C:\Users\saiki\OneDrive\Desktop\Customer Churn Prediction Project\CustomerChurnDataset.xlsx")
df.head()

,Customer_ID,Age,Gender,Location,Tenure,Contract_Type,Subscription_Plan,Monthly_Charges,Total_Charges,Payment_Method,Internet_Service,Login_Frequency,Support_Tickets,Complaints,Avg_Session_Duration,Last_Login,Churn
0,CUST133554,57.0,Male,Bengaluru,35.0,One Year,Premium,1133.84,39207.18,Debit Card,Fiber,14.0,3.0,0.0,57.0,2026-06-28,1
1,CUST109428,70.0,Female,Jaipur,29.0,One Year,Standard,725.32,19918.12,Net Banking,Mobile Data,15.0,3.0,1.0,15.7,2026-08-07,0
2,CUST100200,73.0,Male,Bengaluru,46.0,Two Year,Standard,865.06,41611.82,Debit Card,Fiber,10.0,1.0,0.0,35.9,2026-07-23,0
3,CUST112448,26.0,Female,Ahmedabad,59.0,One Year,Basic,399.95,26431.87,Credit Card,Fiber,12.0,2.0,3.0,30.6,2026-06-17,0
4,CUST139490,31.0,Female,Kochi,24.0,Month-to-Month,Premium,1141.21,30201.24,Net Banking,Fiber,15.0,1.0,0.0,19.2,2026-07-11,1

In [4]:
df.shape

(50000, 17)

In [5]:
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'Location', 'Tenure', 'Contract_Type',
       'Subscription_Plan', 'Monthly_Charges', 'Total_Charges',
       'Payment_Method', 'Internet_Service', 'Login_Frequency',
       'Support_Tickets', 'Complaints', 'Avg_Session_Duration', 'Last_Login',
       'Churn'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Customer_ID           50000 non-null  object
 1   Age                   49500 non-null  float64
 2   Gender                49600 non-null  object
 3   Location              49500 non-null  object
 4   Tenure                49600 non-null  float64
 5   Contract_Type         49500 non-null  object
 6   Subscription_Plan     49600 non-null  object
 7   Monthly_Charges       49400 non-null  float64
 8   Total_Charges         49400 non-null  float64
 9   Payment_Method        49551 non-null  object
 10  Internet_Service      46163 non-null  object
 11  Login_Frequency       49400 non-null  float64
 12  Support_Tickets       49600 non-null  float64
 13  Complaints            49600 non-null  float64
 14  Avg_Session_Duration  49500 non-null  float64
 15  Last_Login            49500 non-null  datetime64[ns]
 16  Churn                 50000 non-null  int64
dtypes: datetime64[ns](1), float64(8), int64(1), object(7)
memory usage: 6.5+ MB

In [7]:
df.describe()

,Age,Tenure,Monthly_Charges,Total_Charges,Login_Frequency,Support_Tickets,Complaints,Avg_Session_Duration,Last_Login,Churn
count,49500.000000,49600.000000,49400.000000,49400.000000,49400.000000,49600.000000,49600.000000,49500.000000,49500,50000.000000
mean,46.498465,36.436169,758.780450,27681.403844,11.969231,2.198710,0.699214,42.074218,2026-07-28 20:52:14.836363264,0.385520
min,18.000000,1.000000,199.000000,199.000000,0.000000,0.000000,0.000000,5.000000,2026-06-14 00:00:00,0.000000
25%,32.000000,18.000000,526.670000,12202.372500,9.000000,1.000000,0.000000,31.300000,2026-07-06 00:00:00,0.000000
50%,47.000000,36.000000,738.950000,24044.815000,12.000000,2.000000,1.000000,41.900000,2026-07-29 00:00:00,0.000000
75%,61.000000,54.250000,901.610000,39084.580000,15.000000,3.000000,1.000000,52.800000,2026-08-21 00:00:00,1.000000
max,75.000000,72.000000,1505.020000,110216.360000,32.000000,11.000000,6.000000,106.800000,2026-09-12 00:00:00,1.000000
std,16.761301,20.807940,273.356287,19794.130888,4.986358,1.481796,0.838228,15.811317,NaN,0.486723

In [8]:
df.describe(include="object")

,Customer_ID,Gender,Location,Contract_Type,Subscription_Plan,Payment_Method,Internet_Service
count,50000,49600,49500,49500,49600,49551,46163
unique,48000,3,10,3,3,6,4
top,CUST109061,Female,Pune,Month-to-Month,Basic,UPI,Fiber
freq,2,24411,5047,27222,19933,13939,17399

In [9]:
df.isnull().sum()

Customer_ID                0
Age                      500
Gender                   400
Location                 500
Tenure                   400
Contract_Type            500
Subscription_Plan        400
Monthly_Charges          600
Total_Charges            600
Payment_Method           449
Internet_Service        3837
Login_Frequency          600
Support_Tickets          400
Complaints               400
Avg_Session_Duration     500
Last_Login               500
Churn                      0
dtype: int64

In [10]:
missing_percentage = (df.isnull().sum()/len(df)) * 100
missing_percentage.sort_values(ascending=False)

Internet_Service        7.674
Total_Charges           1.200
Monthly_Charges         1.200
Login_Frequency         1.200
Last_Login              1.000
Location                1.000
Contract_Type           1.000
Age                     1.000
Avg_Session_Duration    1.000
Payment_Method          0.898
Gender                  0.800
Tenure                  0.800
Subscription_Plan       0.800
Support_Tickets         0.800
Complaints              0.800
Customer_ID             0.000
Churn                   0.000
dtype: float64

In [11]:
df.duplicated().sum()

np.int64(1500)

In [12]:
df[df.duplicated()]

,Customer_ID,Age,Gender,Location,Tenure,Contract_Type,Subscription_Plan,Monthly_Charges,Total_Charges,Payment_Method,Internet_Service,Login_Frequency,Support_Tickets,Complaints,Avg_Session_Duration,Last_Login,Churn
1690,CUST109392,56.0,Female,Hyderabad,39.0,One Year,Standard,687.14,25163.53,Debit Card,DSL,6.0,1.0,0.0,40.7,2026-07-12,1
1716,CUST132059,21.0,Male,Jaipur,7.0,One Year,Standard,707.12,5100.86,Net Banking,DSL,11.0,6.0,0.0,49.3,2026-06-19,1
2056,CUST115478,23.0,Other,Mumbai,43.0,Month-to-Month,Standard,863.27,33613.92,Cash,Fiber,18.0,3.0,1.0,32.2,2026-07-18,1
2506,CUST101163,67.0,Female,Jaipur,57.0,Two Year,Basic,615.50,38109.38,Debit Card,Cable,22.0,0.0,1.0,53.2,2026-09-03,0
2831,CUST133932,60.0,Male,Jaipur,11.0,One Year,Basic,519.12,5881.88,Credit Card,DSL,11.0,4.0,3.0,51.6,2026-08-06,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49902,CUST129126,75.0,Female,Kochi,26.0,Month-to-Month,Standard,804.04,20599.58,Credit Card,Fiber,4.0,2.0,2.0,55.0,2026-07-13,1
49903,CUST104233,53.0,Male,Jaipur,50.0,Two Year,Basic,464.07,21477.61,UPI,Cable,16.0,1.0,0.0,70.5,2026-06-19,0
49933,CUST113418,53.0,Female,Pune,32.0,Month-to-Month,Basic,535.80,15693.85,Auto Debit,Fiber,16.0,2.0,2.0,23.1,2026-08-06,0
49947,CUST123991,39.0,Female,Ahmedabad,67.0,Month-to-Month,Standard,947.94,62830.60,UPI,Mobile Data,25.0,0.0,1.0,32.2,2026-06-16,0
49982,CUST137820,48.0,Male,Delhi,61.0,Month-to-Month,Basic,465.64,30190.99,Net Banking,Mobile Data,16.0,2.0,1.0,44.1,2026-09-02,0

In [13]:
df["Churn"].value_counts()

Churn
0    30724
1    19276
Name: count, dtype: int64

In [14]:
df["Churn"].value_counts(normalize=True)*100

Churn
0    61.448
1    38.552
Name: proportion, dtype: float64

In [15]:
df["Gender"].unique()

array(['Male', 'Female', nan, 'Other'], dtype=object)

In [16]:
df["Contract_Type"].unique()

array(['One Year', 'Two Year', 'Month-to-Month', nan], dtype=object)

In [17]:
df["Payment_Method"].unique()

array(['Debit Card', 'Net Banking', 'Credit Card', 'Auto Debit', 'UPI',
       'Cash', nan], dtype=object)

In [19]:
df["Age"].describe()

count    49500.000000
mean        46.498465
std         16.761301
min         18.000000
25%         32.000000
50%         47.000000
75%         61.000000
max         75.000000
Name: Age, dtype: float64

In [20]:
df["Monthly_Charges"].describe()

count    49400.000000
mean       758.780450
std        273.356287
min        199.000000
25%        526.670000
50%        738.950000
75%        901.610000
max       1505.020000
Name: Monthly_Charges, dtype: float64

In [21]:
df["Tenure"].describe()

count    49600.000000
mean        36.436169
std         20.807940
min          1.000000
25%         18.000000
50%         36.000000
75%         54.250000
max         72.000000
Name: Tenure, dtype: float64